### ISSUE TITLE
For Background Connectivity the app must stay in background

### ISSUE THREAD

**Issue by helifrank** [automat-berlin/afone#4]
For Background Connectivity the app must stay in background.
Other softphones can completely closed with Callkit and Pushkit.
iOS 13.4.1

**Comment by shadzik** [comment]
Hey, thanks for taking the time and reporting bugs. In background mode, an App in iOS gets up to 3min of computing time - then it is possible to receive a call - although PushKit is implemented for //afone, it's not being used in the App Store version (due to push notifications not being set up for your custom SIP server). If you're using the App Store version, please consider building //afone yourself and setting up push notifications, then your problems should be gone.
